### ISSUE TITLE
Node.js 8 has been deprecated in Firebase

### ISSUE THREAD

**Issue by armonkolaei** [chat21/chat21-cloud-functions#18]
Node.js 8 has been deprecated.
From 15 Feb 2021, we'll no longer support new deploys or updates of Node.js 8 functions.
Starting 15 Mar 2021, we'll no longer support executions of existing Node.js 8 functions.

**Comment by Flxleo** [comment]
Same issue here, found this though: https://stackoverflow.com/questions/62475218/firebase-init-node-js-8-has-been-deprecated 

as it seems you can re-deploy using node-10 runtime to circumvent the error

**Comment by andrealeo83** [comment]
Upgraded to 1.0.29
