### ISSUE TITLE
Documentation on how to receive messages ??

### ISSUE THREAD

**Issue by jakoberpf** [chat21/chat21-cloud-functions#24]
Heylo,

very nice project by the way. I am missing some documentation on how messages are received. I saw that in the demo there is an API call for GET .../api/.../messages but I don't see this in the chat-api function nor does a GET work on this endpoint with my deployment. 

- code21-node-sdk 

Any hint on where is can find some doc, code, or info on how to receive messages?

**Comment by andrealeo83** [comment]
The messages are received using Google Firebase API. You can find how the messages are received viewing the Chat21 clients: 
- https://github.com/chat21/chat21-web-widget
- https://github.com/chat21/chat21-ionic
- https://github.com/chat21/chat21-android-sdk

**Comment by jakoberpf** [comment]
Okey thx...
