### ISSUE TITLE
package.json missing

### ISSUE THREAD

**Issue by TalhaBinAfzal** [chat21/chat21-cloud-functions#3]
I have clone the project now when I install it I get an error package.json not found. Can you provide me the json required to this file? Waiting for your reply..

**Comment by andrealeo83** [comment]
The file package.json is under functions directory. So you must run : cd functions and after run: npm install    as described here :https://github.com/chat21/chat21-cloud-functions/blob/master/README.md#project-setup

**Comment by TalhaBinAfzal** [comment]
I have done the same I run cd function and then cd install when I run cd install I am getting that error.. even I downloaded function more than once, package.json file is missing... Can you provide me that file?

**Comment by andrealeo83** [comment]
Hi this is the package.json https://github.com/chat21/chat21-cloud-functions/blob/master/functions/package.json. You can download the raw version here: https://raw.githubusercontent.com/chat21/chat21-cloud-functions/master/functions/package.json

 Don't you find the file package.json under functions directory?
