### ISSUE TITLE
Make it clearer about using the group id when sending group messages.

### ISSUE THREAD

**Issue by grandadmiralmcb** [chat21/chat21-cloud-functions#5]
documentation on this page
https://github.com/chat21/chat21-cloud-functions/blob/master/docs/api.md#send-a-message

fails to mention any changes between sending a direct message and a group messaging including the group id (as a substitute for the recipient id) and specifying the channel type as "group" that should be part  invocation

**Comment by andrealeo83** [comment]
Please re-open the documentation : https://github.com/chat21/chat21-cloud-functions/blob/master/docs/api.md#send-a-message

Now send message has channel_type and a send group example
